USE PROJECT;

create table PATIENT (
PATIENT_ID int primary key, 
PT_FNAME VARCHAR(20),
PT_LNAME VARCHAR(20),
PT_SEX VARCHAR(2),
PT_DOB DATETIME NOT NULL,
PT_WEIGHT INT,
PT_ETHNICITY VARCHAR(15)
);

#INSERT INTO PATIENT VALUE(1,"John", "Doe", "M", "20031225", 125, "White");



create TABLE SURGEON (
SURGEON_ID INT PRIMARY KEY,
S_FNAME VARCHAR(20),
S_LNAME VARCHAR(20),
S_SPECIALTY VARCHAR(30),
S_SEX VARCHAR(2),
S_DOB DATETIME NOT NULL,
S_HIREDATE DATETIME NOT NULL
);

#INSERT INTO SURGEON VALUE(1, "Amy", "Smith", "Pediatrics", "F", "19890804", "20101109");

CREATE TABLE PROCEDURES(
PROCEDURE_ID INT PRIMARY KEY,
SPECIALTY VARCHAR(30),
ANATOMICAL_AREA VARCHAR(30),
DESCRIPT VARCHAR(100),
EST_TIMELENGTH time not null);

#INSERT INTO PROCEDURES VALUE(1, "Pediatrics", "Leg", "yadda yadda yadda yadda", "1:00:00");

CREATE TABLE STAFF(
EMP_ID INT PRIMARY KEY,
EMP_FNAME VARCHAR(30),
EMP_LNAME VARCHAR(30),
EMP_ROLE VARCHAR(25),
EMP_SEX VARCHAR(2),
EMP_HIREDATE DATETIME NOT NULL
);

#INSERT INTO STAFF VALUE(1, "Stan", "Smith", "Anesthesiologist", "M", "19990913");

CREATE TABLE INSTRUMENTS(
TRAY_ID INT PRIMARY KEY,
TRAY_NAME VARCHAR(20),
VENDOR VARCHAR(30),
QTY_PIECES int
);

#INSERT INTO INSTRUMENTS VALUE(1, "Tray", "Tray Inc.", 5);

CREATE TABLE ADVERSE(
INCIDENT_ID INT PRIMARY KEY,
INCIDENT_DESCRIPTION VARCHAR(100)
);




CREATE TABLE SURGERY_EVENT(
SURGERY_ID INT PRIMARY KEY, PATIENT_ID INT, SURGEON_ID INT, PROCEDURE_ID INT, TRAY_ID INT, STAFF_ID INT,
CONSTRAINT PATIENT_KEY FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
CONSTRAINT SURGEON_KEY FOREIGN KEY (SURGEON_ID) REFERENCES SURGEON(SURGEON_ID),
CONSTRAINT PROCEDURE_KEY FOREIGN KEY (PROCEDURE_ID) REFERENCES PROCEDURES(PROCEDURE_ID),
CONSTRAINT TRAY_KEY FOREIGN KEY (TRAY_ID) REFERENCES INSTRUMENTS(TRAY_ID),
CONSTRAINT STAFF_KEY FOREIGN KEY (STAFF_ID) REFERENCES STAFF(EMP_ID),
WHEELS_IN DATETIME NOT NULL,
START_TIME DATETIME NOT NULL,
END_TIME DATETIME NOT NULL,
WHEELS_OUT DATETIME NOT NULL,
SURGERY_DATE DATE NOT NULL,
ROOM_NUMBER INT
);



INSERT INTO SURGERY_EVENT VALUE(1,1,1,1,1,1, "20201212121212", "20201212", "20201212", "20201212", "20050530", 5);

SELECT * FROM SURGERY_EVENT;

select s.S_FNAME, s.S_LNAME, se.SURGERY_ID, se.WHEELS_IN
from surgeon as s
INNER JOIN SURGERY_EVENT as se
on se.SURGEON_ID = s.SURGEON_ID;

select S_FNAME, EMP_FNAME
from SURGERY_EVENT
inner join surgeon
	on surgeon.SURGEON_ID = SURGERY_EVENT.SURGEON_ID
inner join STAFF
    on STAFF.EMP_ID = SURGERY_EVENT.STAFF_ID;

SELECT surgery_event.ENCOUNTER_ID, surgery_event.SURGERY_DATE, DLookUp("S_LNAME","surgeon","[SURGEON_ID]=" & [SURGEON_ID]) & ", " & DLookUp("S_FNAME","surgeon","[SURGEON_ID]=" & [SURGEON_ID]) AS SURGEON, surgery_event.OR_SUITE, DLookUp("EMP_LNAME","staff","[EMP_ID]=" & [ANES_ID]) & ", " & DLookUp("EMP_FNAME","staff","[EMP_ID]=" & [ANES_ID]) AS ANES, DLookUp("EMP_LNAME","staff","[EMP_ID]=" & [SCRUB_ID]) & ", " & DLookUp("EMP_FNAME","staff","[EMP_ID]=" & [SCRUB_ID]) AS SCRUB, DLookUp("EMP_LNAME","staff","[EMP_ID]=" & [NURSE_ID]) & ", " & DLookUp("EMP_FNAME","staff","[EMP_ID]=" & [NURSE_ID]) AS NURSE, surgery_event.CPT_CODE, surgery_event.CPT_DESC, surgery_event.BOOKED_TIME, surgery_event.OR_SCHEDULE, surgery_event.WHEELS_IN, surgery_event.START_TIME, surgery_event.END_TIME, surgery_event.WHEELS_OUT
FROM surgery_event
WHERE (((surgery_event.SURGEON_ID)=[ENTER: SURGEON_ID]));
